import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { absoluteBriefUrl } from "@/lib/distribution/base-url";
import { getPublicBrief } from "@/lib/distribution/public-brief";
import ListenClient from "./listen-client";

export const dynamic="force-dynamic";
type Params={slug:string};
export async function generateMetadata({params}:{params:Promise<Params>}):Promise<Metadata>{
  const {slug}=await params; const brief=await getPublicBrief(slug); if(!brief)return {title:"Brief not found",robots:{index:false,follow:false}};
  const description=(brief.deck||brief.answer).replace(/\s+/g," ").slice(0,155);
  return {title:brief.title,description,alternates:{canonical:absoluteBriefUrl(brief.slug)},openGraph:{type:"article",title:brief.title,description,url:absoluteBriefUrl(brief.slug),siteName:"Briefs",publishedTime:brief.createdAt||undefined,modifiedTime:brief.lastVerifiedAt||brief.updatedAt||undefined},twitter:{card:"summary_large_image",title:brief.title,description},robots:{index:true,follow:true}};
}

export default async function BriefPage({params}:{params:Promise<Params>}){
  const {slug}=await params; const brief=await getPublicBrief(slug); if(!brief){notFound();throw new Error("Brief not found");}
  const sourceMap=new Map<string,{name:string;url:string;tier:string}>();for(const claim of brief.claims)for(const ev of claim.evidence)sourceMap.set(ev.sourceId,{name:ev.sourceName,url:ev.sourceUrl,tier:ev.tier});
  const verified=brief.lastVerifiedAt||brief.updatedAt; const canonical=absoluteBriefUrl(brief.slug);
  const articleJsonLd={"@context":"https://schema.org","@type":"Article",headline:brief.title,description:brief.deck,url:canonical,mainEntityOfPage:canonical,datePublished:brief.createdAt||verified,dateModified:verified,author:{"@type":"Organization",name:"Briefs"},publisher:{"@type":"Organization",name:"Briefs",url:canonical.split("/briefs/")[0]},isAccessibleForFree:true,citation:[...sourceMap.values()].map(s=>s.url)};
  const breadcrumbJsonLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Briefs",item:canonical.split("/briefs/")[0]},{"@type":"ListItem",position:2,name:"Explore Briefs",item:`${canonical.split("/briefs/")[0]}/briefs`},{"@type":"ListItem",position:3,name:brief.title,item:canonical}]};
  const listenText=[brief.answer,brief.whyItMatters,brief.context,...brief.claims.slice(0,8).map(c=>`${c.predicate}: ${c.value}`)].filter(Boolean).join(" ");
  return <main className="section brief public-brief"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleJsonLd).replace(/</g,"\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbJsonLd).replace(/</g,"\\u003c")}}/><nav className="breadcrumb"><Link href="/briefs">Briefs</Link><span>→</span><span>{brief.title}</span></nav><div className="public-brief-head"><div><span className="pill">{brief.dynamic?"LIVING":"EVERGREEN"} · {brief.freshnessScore}% FRESH</span><h1>{brief.title}</h1><p className="muted brief-deck">{brief.deck}</p></div><ListenClient title={brief.title} text={listenText}/></div><div className="brief-authority-meta"><span>{brief.readingMinutes} min read</span><span>{verified?`Verified ${new Date(verified).toLocaleDateString()}`:"Verification pending"}</span><span>{brief.sourceMode==="database"?"Living knowledge DB":"Verified baseline"}</span></div><div className="rule"/><h2>The answer</h2><p>{brief.answer}</p>{brief.whyItMatters&&<><h2>Why it matters</h2><p>{brief.whyItMatters}</p></>}{brief.context&&<><h2>Context</h2><p>{brief.context}</p></>}<div className="rule"/><h2>Tracked claims</h2>{brief.claims.length===0?<p className="muted">No public structured claims are attached yet.</p>:brief.claims.map(claim=><article className="card public-claim" key={claim.id}><div className="claim-title"><strong>{claim.predicate}</strong><span className="pill">{claim.verificationStatus} · {claim.confidence}</span></div><p>{claim.value}</p>{claim.evidence.length>0&&<details><summary>{claim.evidence.length} supporting source{claim.evidence.length===1?"":"s"}</summary><div className="claim-evidence">{claim.evidence.map((ev,index)=><a href={ev.sourceUrl} rel="noreferrer" target="_blank" key={`${ev.sourceId}-${index}`}><strong>{ev.sourceName}</strong><span>Tier {ev.tier}</span>{ev.excerpt&&<small>{ev.excerpt}</small>}</a>)}</div></details>}</article>)}{brief.watchNext.length>0&&<><h2>What to watch</h2><ul className="brief-watch">{brief.watchNext.map(item=><li key={item}>{item}</li>)}</ul></>}<section className="distribution-tools"><h2>Use this Brief</h2><div><a href={`/api/export?q=${encodeURIComponent(brief.title)}&format=markdown`}>Markdown</a><a href={`/api/export?q=${encodeURIComponent(brief.title)}&format=csv`}>CSV</a><a href={`/api/export?q=${encodeURIComponent(brief.title)}&format=json`}>JSON</a><a href={`/brief-me?q=${encodeURIComponent(brief.title)}`}>Ask a follow-up</a></div></section>{sourceMap.size>0&&<section><h2>Evidence</h2><div className="brief-sources">{[...sourceMap.entries()].map(([id,source])=><a key={id} href={source.url} target="_blank" rel="noreferrer"><strong>{source.name}</strong><span>Tier {source.tier}</span></a>)}</div></section>}<footer className="brief-meta">Canonical: {canonical} · Knowledge cutoff {verified?new Date(verified).toLocaleString():"not established"}</footer></main>;
}
