import type { BriefResult } from "@/lib/types";

function escCsv(value:string){return `"${String(value).replace(/"/g,'""')}"`;}
export function safeFilename(subject:string){return subject.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"brief";}

export function renderBriefMarkdown(result:BriefResult){
  const lines=[`# ${result.subject}`,"",result.summary,"",`**Confidence:** ${result.confidence}`,`**Knowledge cutoff:** ${result.knowledgeCutoff}`];
  if(result.whyItMatters) lines.push("","## Why it matters","",result.whyItMatters);
  if(result.keyChanges.length) lines.push("","## What changed","",...result.keyChanges.map(c=>`- ${c.summary} (${c.changedAt.slice(0,10)})`));
  if(result.keyFacts.length) lines.push("","## Key facts","",...result.keyFacts.map(f=>`- **${f.label}:** ${f.value}`));
  if(result.watchItems.length) lines.push("","## What to watch","",...result.watchItems.map(item=>`- ${item}`));
  if(result.sources.length) lines.push("","## Evidence","",...result.sources.map(s=>`- [${s.name}](${s.url}) — Tier ${s.tier}`));
  lines.push("","---",`Generated by Briefs at ${result.generatedAt}.`);
  return lines.join("\n");
}

export function renderBriefCsv(result:BriefResult){
  const rows:Array<[string,string,string,string]>=[["section","label","value","source_ids"]];
  rows.push(["summary","The brief",result.summary,""]);
  if(result.whyItMatters) rows.push(["context","Why it matters",result.whyItMatters,""]);
  for(const fact of result.keyFacts) rows.push(["fact",fact.label,fact.value,fact.sourceIds.join("|")]);
  for(const change of result.keyChanges) rows.push(["change",change.changedAt,change.summary,""]);
  for(const source of result.sources) rows.push(["source",source.name,source.url,source.id]);
  return rows.map(row=>row.map(escCsv).join(",")).join("\n");
}

export function renderBriefText(result:BriefResult){
  return [result.subject,result.summary,result.whyItMatters&&`Why it matters: ${result.whyItMatters}`,result.keyFacts.length&&`Key facts:\n${result.keyFacts.map(f=>`• ${f.label}: ${f.value}`).join("\n")}`,result.watchItems.length&&`What to watch:\n${result.watchItems.map(i=>`• ${i}`).join("\n")}`].filter(Boolean).join("\n\n");
}
